<?php
// version: 0.4a beta
//
// Hunter Configuration File
// 
// Do not edit this file manually unless you know what you are doing.
//
// 

$adminPassword="extreme";
$adminEmail="lovster6@gmail.com";

$database="a6877900_calc";
$user="a6877900_lovsan";
$password="a6877900";
$host="mysql2.000webhost.com";
$tableName="sk_hunter";



$x_min=1;
$x_max=2;
$y_min=1;
$y_max=20;
$server="s1";

$databaseRunning=1;

$HNPassword="12345";
$maxHoursInDatabase=50;
$serverMSG="SK Hunter: select dropdown to view changes";
$serverMSGcolor="A0A0A0";
$MSGisLink=0;
$MSGlinkURL="http://skarchive.net76.net/hunter/server.php";

$useAccessWhiteList=0;
$accessWhiteList=array (  'fusorman' =>   array (    0 => 'magnusnet@gmail.com',    1 => 1,    2 => 5,  ),  'Cumdog Millionaire' =>   array (    0 => 'lovster6@gmail.com',    1 => 1,    2 => 13,  ),  'new user nr 3' =>   array (    0 => '',    1 => 0,    2 => 0,  ),);
